version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "vcpkg"
    directory: "/"
    schedule:
      interval: weekly
    exclude-paths:
      - "eng/common/**"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    exclude-paths:
      - "eng/common/**"
